src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Models/Asesor/AsesorIndexModel.cs
using EscuelaNet.Dominio.Conocimientos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EscuelaNet.Presentacion.Conocimientos.Web.Models
{
    public class AsesorIndexModel
    {
        public string Titulo { get; set; }
        public int IdCategoria { get; set; }
        public int IdCono { get; set; }
        public List<Asesor> Asesores { get; set; }
    }
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Models/Asesor/NuevoAsesorModel.cs
using EscuelaNet.Dominio.Conocimientos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EscuelaNet.Presentacion.Conocimientos.Web.Models
{
    public class NuevoAsesorModel
    {
        public string Titulo { get; set; }
        public int IdCate { get; set; }
        public int IdConocimiento { get; set; }
        public int IdAs { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Disponibilidad Disponibilidad { get; set; }
        public string Idioma { get; set; }
        public String Pais { get; set; }
        //public int Id { get; set; }
    }
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Models/Conocimiento/ConocimientoIndexModel.cs
using EscuelaNet.Dominio.Conocimientos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EscuelaNet.Presentacion.Conocimientos.Web.Models
{
    public class ConocimientoIndexModel
    {
        public string Titulo { get; set; }
        public int IdCategoria { get; set; }
        public string Nombre { get; set; }
        public IList<Conocimiento> Conocimientos { get; set; }
        
    }
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Models/Conocimiento/NuevaConocimientoModel.cs
using EscuelaNet.Dominio.Conocimientos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EscuelaNet.Presentacion.Conocimientos.Web.Models
{
    public class NuevaConocimientoModel
    {
        public string Titulo { get; set; }
        public int IdCate { get; set; }
        public int IdConocimiento { get; set; }
        public string Nombre { get; set; }
        public Demanda Demanda { get; set; }
    }
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Controllers/AsesorController.cs
//using EscuelaNet.Presentacion.Conocimientos.Web.Infraestructura;
using EscuelaNet.Presentacion.Conocimientos.Web.Models;
using EscuelaNet.Dominio.Conocimientos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EscuelaNet.Infraestructura.Conocimientos.Repositorios;

namespace EscuelaNet.Presentacion.Categorias.Web.Controllers
{
    public class AsesorController : Controller
    {
        private IAsesorRepository _asesorrepository;
        private ICategoriaRepository _categoriarepository;
        public ActionResult Index()
        {
            var asesor = _asesorrepository.ListAsesor();

            var model = new AsesorIndexModel()
            {
                Titulo = "Asesores",
                Asesores = asesor
            };

            return View(model);
        }

        public ActionResult New()
        {
            var model = new NuevoAsesorModel()
            {
                Titulo = "Nuevo Asesor"
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult New(NuevoAsesorModel model)
        {
            if (!string.IsNullOrEmpty(model.Nombre))
            {
                try
                {
                    var asesor = new Asesor(model.Nombre, model.Apellido, model.Idioma, model.Pais);
                    _asesorrepository.Add(asesor);
                    _asesorrepository.UnitOfWork.SaveChanges();

                    TempData["success"] = "¡Nuevo asesor creado correctamente!";
                    return RedirectToAction("Index");

                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }

            }
            else
            {
                TempData["error"] = "Texto vacio, ingrese todos los datos solicitados";
                return View(model);
            }
        }

        public ActionResult Edit(int id)
        {
            if (id <= 0)
            {
                TempData["error"] = "Id no valido";
                return RedirectToAction("Index");
            }
            else
            {
                var asesor = _asesorrepository.GetAsesor(id);
                var model = new NuevoAsesorModel()
                {
                    Titulo = "Editar el Asesor: " + asesor.Nombre + asesor.Apellido,
                    Nombre = asesor.Nombre,
                    Apellido = asesor.Apellido,
                    Disponibilidad = asesor.Disponibilidad,
                    Idioma = asesor.Idioma,
                    Pais = asesor.Pais,
                    IdAs=id
                };
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Edit(NuevoAsesorModel model)
        {
            if (!string.IsNullOrEmpty(model.Nombre))
            {
                try
                {
                    var asesor = _asesorrepository.GetAsesor(model.IdAs);
                    asesor.Nombre = model.Nombre;
                    asesor.Apellido = model.Apellido;
                    asesor.Disponibilidad = model.Disponibilidad;
                    asesor.Idioma = model.Idioma;
                    asesor.Pais = model.Pais;

                    _asesorrepository.Update(asesor);
                    _asesorrepository.UnitOfWork.SaveChanges();

                    TempData["success"] = "¡Conocimiento Modificado Correctamente!";
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    TempData["error"] = e.Message;
                    return View(model);
                }
            }
            else
            {
                TempData["error"] = "Texto vacio";
                return View(model);
            }
        }

        public ActionResult Delete(int id)
        {
            if (id <= 0)
            {
                TempData["error"] = "Id no valido";
                return RedirectToAction("Index");
            }
            else
            {
                var asesor = _asesorrepository.GetAsesor(id);

                var model = new NuevoAsesorModel()
                {
                    Nombre = asesor.Nombre,
                    Apellido = asesor.Apellido,
                    Idioma = asesor.Idioma,
                    Pais = asesor.Pais,
                    IdAs = id,
                };
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Delete(NuevoAsesorModel model)
        {
            try
            {
                var asesor = _asesorrepository.GetAsesor(model.IdAs);
                _asesorrepository.Delete(asesor);
                _asesorrepository.UnitOfWork.SaveChanges();

                TempData["success"] = "¡Asesor borrado correctamente!";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return View(model);
            }
        }

        //public ActionResult Conocimiento(int id)
        //{
        //    var asesor = _asesorrepository.GetAsesor(id);
        //    var model = new AsesorConocimientoModel()
        //    {
        //        Asesor = asesor,
        //        Conocimientos = asesor.Conocimientos.ToList()
        //    };
        //    return View(model);
        //}
        public ActionResult DeleteConocimmiento(int id, int asesor)
        {
            var asesorBuscado = _asesorrepository.GetAsesor(asesor);
            var conocimientobuscado = asesorBuscado.Conocimientos.First(c => c.ID == id);
            var model = new NuevoAsesorConocimientoModel()
            {
                NombreConocimiento = conocimientobuscado.Nombre + " " + conocimientobuscado.Demanda,
                IDAsesor = asesor,
                NombreAsesor = asesorBuscado.Nombre + " " + asesorBuscado.Apellido,
                IDConocimiento = id,
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult DeleteConocimmiento(NuevoAsesorConocimientoModel model)
        {
            try
            {
                var asesorBuscado = _asesorrepository.GetAsesor(model.IDAsesor);
                var conocimientobuscado = asesorBuscado.Conocimientos.First(c => c.ID == model.IDConocimiento);
                asesorBuscado.pullConocimiento(conocimientobuscado);

                _asesorrepository.Update(asesorBuscado);
                _asesorrepository.UnitOfWork.SaveChanges();

                TempData["success"] = "¡Asesor borrado correctamente!";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return View(model);
            }
        }
        public ActionResult NewConocimiento(int id)
        {
            var asesor = _asesorrepository.GetAsesor(id);
            var categorias = _categoriarepository.ListCategoria();
            var conocimientos = new List<Conocimiento>();

            foreach(var categoria in categorias)
            {
                foreach (var conocimientoEnCategoria in categoria.Conocimientos)
                {
                    conocimientos.Add(conocimientoEnCategoria);
                };
            }
            var model = new NuevoAsesorConocimientoModel()
            {
                IDAsesor = id,
                NombreAsesor = asesor.Nombre,
                Conocimientos = conocimientos
            };
            return View(model);
        }

        //[HttpPost]
        //public ActionResult NewConocimiento(NuevoAsesorConocimientoModel model)
        //{
        //    try
        //    {
        //        var asesorBuscado = _asesorrepository.GetAsesor(model.IDAsesor);
        //        var conocimientoBuscado = _categoriarepository.GetConocimieto(model.IDConocimiento);

        //        var bandera = true;
        //        var bandera2 = true;

        //        foreach (var conocimientoencontrado in asesorBuscado.Conocimientos)
        //        {
        //            if (conocimientoencontrado.IDCategoria != conocimientoBuscado.Categoria.ID)
        //            {
        //                bandera = false;
        //            }
        //            if (conocimientoencontrado.ID == model.IDConocimiento)
        //            {
        //                bandera2 = false;
        //            }
        //        }
        //        if (bandera && bandera2)
        //        {
        //            _categoriarepository.AddAsesor(conocimientoBuscado, asesorBuscado);
        //            _categoriarepository.Update(conocimientoBuscado.Categoria);
        //            _categoriarepository.UnitOfWork.SaveChanges();

        //            TempData["success"] = "¡Asesor Creado Correctamente!";
        //            return RedirectToAction("../Asesor/Conocimiento/" + model.IDAsesor);
        //        }
        //        else if (bandera2)
        //        {
        //            TempData["error"] = "" + "¡ERROR! El asesor fue vinculado a un conocimiento de otra categoria";
        //            return RedirectToAction("../Asesor/Conocimiento/" + model.IDAsesor);
        //        }
        //        else
        //        {
        //            TempData["error"] = "¡ERROR! El asesor ya fue vinculado a este conocimiento";
        //            return RedirectToAction("../Asesor/Conocimiento/" + model.IDAsesor);
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        TempData["error"] = ex.Message;
        //        return RedirectToAction("../Asesor/Conocimiento/" + model.IDAsesor);
        //    }

            //    asesorBuscado.pushConocimiento(conocimientoBuscado);
            //    repositorio.Update(asesorBuscado);

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Views/Conocimiento/Asesor.cshtml
@model EscuelaNet.Presentacion.Conocimientos.Web.Models.AsesorConocimientoModel

<div class="row">
    <div class="col-md-5">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Asesores del conocimiento: "@Model.Conocimiento.Nombre" de la categoria: "@Model.Conocimiento.NombreCategoria"</h3>


                <label class="text-success">@TempData["success"]</label>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table class="table table-bordered">
                    <tbody>
                        <tr>

                            <th style="width: 10px">#</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Demanda</th>
                            <th>Idioma</th>
                            <th>Pais</th>
                            <th>Acciones</th>
                        </tr>

                        @foreach (var asesor in Model.Asesores)
                        {
                            <tr>
                                <td>@asesor.ID</td>
                                <td>@asesor.Nombre</td>
                                <td>@asesor.Apellido</td>
                                <td>@asesor.Disponibilidad</td>
                                <td>@asesor.Idioma</td>
                                <td>@asesor.Pais</td>
                                

                                <td>
                                    <a href="/Asesor/Edit/@asesor.ID" title="Editar Asesor" class="btn btn-toolbar">
                                        <label class="label bg-gray"><i class="fa fa-edit"></i> Editar</label>
                                    </a>

                                    <a href="/Conocimiento/DeleteConocimiento/@asesor.ID?conocimiento=@Model.Conocimiento.ID" title="Desvincular asesor del conocimiento" class="btn btn-toolbar">
                                        <label class="label bg-gray"><i class="fa fa-remove"></i> Desvincular</label>
                                    </a>
                                </td>

                            </tr>
                        }


                        <tr>
                            <td colspan="6">
                                <a href="/Conocimiento/NewConocimiento/@Model.Conocimiento.ID" title="Agregar Asesor" class="btn btn-toolbar">
                                    <label class="label bg-gray"><i class="fa fa-plus"></i> Agregar Asesor</label>
                                </a>
                            </td>

                        </tr>
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
                <ul class="pagination pagination-sm no-margin pull-right">
                    <li><a href="#">«</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">»</a></li>
                </ul>
            </div>
        </div>
        <!-- /.box -->
        <!-- /.box -->
    </div>
    <!-- /.col -->
    <!-- /.col -->
</div>

<div>
    @Html.ActionLink("Volver Atras", "../Conocimiento/Index/" )
</div>

@section Scripts{
    <script>
    </script>
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Views/Conocimiento/Delete.cshtml
@model EscuelaNet.Presentacion.Conocimientos.Web.Models.NuevaConocimientoModel

@{
    ViewBag.Title = "Borrar";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Borrar Conocimiento</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IdCate)
                    @Html.HiddenFor(model => model.IdConocimiento)
                    <div class="box-body">
                        <p>
                            ¿Esta seguro de borrar la linea "@Model.Nombre"?
                        </p>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                        <a href="/Conocimiento/Index/@Model.IdCate"> Cancelar</a>
                        @*<button id="cancel" name="cancel" class="btn btn-default" value="1">Cancelar</button>*@

                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>

}
<div>
    @Html.ActionLink("Volver al Incio", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Views/Conocimiento/DeleteAsesor.cshtml
@model EscuelaNet.Presentacion.Conocimientos.Web.Models.NuevoAsesorConocimientoModel
@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Borrar asesor '@Model.NombreAsesor' del conocimiento '@Model.NombreConocimiento' </h3>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm("DeleteAsesor", "Conocimiento", new { }, FormMethod.Post, new { role = "form", data_toggle = "validator", @id = "myform" })))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IDAsesor)
                @Html.HiddenFor(model => model.IDConocimiento)
                <div class="box-body">
                    <p>
                        ¿Está seguro que desea borrar "@Model.NombreConocimiento"?
                    </p>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Aceptar</button>
                    <a href="/Conocimiento/Asesor/@Model.IDAsesor" class="btn btn-primary">Cancelar</a>
                </div>
            }

        </div>
        <!-- /.box -->
    </div>

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Views/Conocimiento/Edit.cshtml
@model EscuelaNet.Presentacion.Conocimientos.Web.Models.NuevaConocimientoModel

@{
    ViewBag.Title = "Editar";
}




    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Nuevo Conocimiento</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm("Edit", "Conocimiento", null,
                       FormMethod.Post, new { role = "form", data_toggle = "validator"}))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IdCate)
                    @Html.HiddenFor(model => model.IdConocimiento)


                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Demanda, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EnumDropDownListFor(m => m.Demanda, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Demanda, "", new { @class = "help-block with errors" })
                        </div>
                    </div>


                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                        <a href="/Conocimiento/Index/@Model.IdCate" class="btn btn-danger">Cancelar</a>
                    </div>


                }

            </div>
            <!-- /.box -->
        </div>

    </div>


<div>
    @Html.ActionLink("Volver Atrás", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Views/Conocimiento/Index.cshtml
@model EscuelaNet.Presentacion.Conocimientos.Web.Models.ConocimientoIndexModel
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">CONOCIMIENTOS   </h3>
                <label class="text-success">@TempData["success"]</label>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>Nombre</th>
                            <th>Demanda</th>
                            <th>Acciones</th>
                        </tr>
                        @foreach (var conocimiento in Model.Conocimientos)
                        {
                            <tr>
                                <td>@conocimiento.ID</td>
                                <td>@conocimiento.Nombre</td>
                                <td>@conocimiento.Demanda</td>
                                <td>
                                    <a href="/Conocimiento/Edit/@conocimiento.ID" title="Editar" class="btn btn-toolbar">
                                        <label class="btn btn-dropbox"><i class="fa fa-edit"></i> Editar</label>

                                        <a href="/Conocimiento/delete/@conocimiento.ID" title="borrar" class="btn btn-toolbar">
                                            <label class="btn btn-default"><i class="fa fa-remove"></i> Borrar</label>

                                </td>
                            </tr>
                        }
                        <tr>
                            <td></td>
                            <td></td>
                            <td>
                                <a href="/Conocimiento/New/@Model.IdCategoria" title="Nuevo" type="button" class="btn btn-success">
                                    Nuevo
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
                <ul class="pagination pagination-sm no-margin pull-right">
                    <li><a href="#">«</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">»</a></li>
                </ul>
            </div>
        </div>
        <!-- /.box -->
        <!-- /.box -->
    </div>
    <!-- /.col -->
    <!-- /.col -->
</div>

@section Scripts{
    <script>
    </script>
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Views/Conocimiento/New.cshtml
@model EscuelaNet.Presentacion.Conocimientos.Web.Models.NuevaConocimientoModel

@{
    ViewBag.Title = "New";
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Nuevo Conocimiento</h3>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm("New", "Conocimiento", null,
                       FormMethod.Post, new { role = "form", data_toggle = "validator", @id = "myForm" }))
            {
                @Html.HiddenFor(model => model.IdCate)

                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="box-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Ingrese el nombre del Conocimiento.", data_minlength = "2" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "help-block with-errors" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Demanda, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EnumDropDownListFor(m => m.Demanda, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Demanda, "", new { @class = "help-block with errors" })
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Crear</button>
                    <a href="/Conocimiento/Index" title="Cancelar" type="button" class="btn btn-danger">Cancelar</a>
                </div>

            }

        </div>
        <!-- /.box -->
    </div>

</div>
<div>
    @Html.ActionLink("Volver al Inicio", "Index")
</div>

@section Scripts {
    <script src="~/lib/1000hz-bootstrap-validator/validator.js"></script>
    <script>
        $(document).ready(function () {
            $('#myForm').validator()
        });
    </script>
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Views/Conocimiento/NewAsesor.cshtml
@model EscuelaNet.Presentacion.Conocimientos.Web.Models.NuevoAsesorConocimientoModel
@{
    ViewBag.Title = "New";
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Nuevo Conocimiento para: @Model.NombreConocimiento</h3>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm("NewAsesor", "Asesor", null,
                FormMethod.Post, new { role = "form", data_toggle = "validator", @id = "myform" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IDConocimiento)
                <div class="box-body">

                    <div class="form-group">
                        @Html.LabelFor(model => model.Conocimientos, htmlAttributes: new { @class = "control-label col-md-2" })
                        <select name="IDConocimiento" class="form-control col-md-2">
                            @foreach (var asesor in Model.Asesores)
                            {
                                <option value="@asesor.ID">@asesor.ID / @asesor.Titulo</option>
                            }
                        </select>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="~/Conocimiento/" class="btn btn-primary">Cancelar</a>
                </div>
            }

        </div>
        <!-- /.box -->
    </div>

</div>

@section Scripts {
    <script src="~/lib/1000hz-bootstrap-validator/validator.js"></script>
    <script>
      $(document).ready(function () {
          $('#myForm').validator()
      });

    </script>