src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/EscuelaNet.Presentacion.Proyectos.Web/Models/LineasIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EscuelaNet.Presentacion.Proyectos.Web.Models
{
    public class LineasIndexModel
    {
        public string Titulo { get; set; }
        public List<LineaDeProduccion> lineaDeProduccion { get; set; }
    }
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/EscuelaNet.Presentacion.Proyectos.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EscuelaNet.Presentacion.Proyectos.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/EscuelaNet.Presentacion.Proyectos.Web/Controllers/LineaDeProduccionController.cs
using EscuelaNet.Presentacion.Proyectos.Web.Infraestructura;
using EscuelaNet.Presentacion.Proyectos.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EscuelaNet.Presentacion.Proyectos.Web.Controllers
{
    public class LineaDeProduccionController : Controller
    {
        // GET: LineaDeProduccion
        public ActionResult Index()
        {
            var lineasDeProduccion = 
                Contexto.Instancia.LineasDeProduccion;
            var model = new LineasIndexModel()
            {
                Titulo = "Primera Prueba"
            };

            return View(model);
        }

        public ActionResult New()
        {
            return View;
        }
        
    }
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/EscuelaNet.Presentacion.Proyectos.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @RenderSection("Header", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Lineas de Produccion", "Index", "LineaDeProduccion")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: true)
</body>
</html>