src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Controllers/EtapasController.cs
using EscuelaNet.Presentacion.Proyectos.Web.Infraestructura;
using EscuelaNet.Presentacion.Proyectos.Web.Models;
using EscuelaNet.Dominio.Proyectos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EscuelaNet.Presentacion.Proyectos.Web.Controllers
{
    public class EtapasController : Controller
    {
        private ILineaRepository _lineaRepository;
        public ITecnologiaRepository _tecnoRepository { get; set; }
        public EtapasController(ILineaRepository lineaRepository, ITecnologiaRepository tecnologiaRepository)
        {
            _lineaRepository = lineaRepository;
            _tecnoRepository = tecnologiaRepository;
        }
        // GET: Etapa
        public ActionResult Index(int idLinea, int idProy)
        {

            var proyecto = _lineaRepository.GetProyecto(idProy);
            if(proyecto.Etapas == null)
            {
                TempData["error"] = "Proyecto sin etapas";
                return RedirectToAction("../Proyectos/Index/?id=" + idLinea);
            }
            var model = new EtapaIndexModel() {
                Etapas = proyecto.Etapas.ToList(),
                IDLinea = idLinea,
                IDProy = idProy
            };

            return View(model);

        }

        public ActionResult New(int id)
        {
            var proyecto = _lineaRepository.GetProyecto(id);
            var model = new NuevaEtapaModel() { IDProy = id };
            return View(model);
        }

        [HttpPost]

        public ActionResult New(NuevaEtapaModel model)
        {
            if (!string.IsNullOrEmpty(model.Nombre))
            {
                try
                {
                    var proyecto = _lineaRepository.GetProyecto(model.IDProy);

                    proyecto.PushEtapa(model.Nombre, model.duracion);
                    _lineaRepository.Update(proyecto.LineaDeProduccion);
                    _lineaRepository.UnitOfWork.SaveChanges();
                    TempData["success"] = "La etapa se ha creado";
                    return RedirectToAction("Index", new { idLinea = model.IDLinea, idProy = model.IDProy });
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }
            } else
            {
                TempData["error"] = "Debe completar ambos campos ";
                return View(model);
            }
        }

        public ActionResult Edit(int idProy, int idLinea, int idEtapa)
        {
            var etapas = _lineaRepository.GetEtapa(idEtapa);
            var proyecto = _lineaRepository.GetProyecto(etapas.IDProyecto);

            var model = new NuevaEtapaModel()
            {
                Nombre = etapas.Nombre,
                ID = idEtapa,
                duracion = etapas.Duracion,
                IDLinea = idLinea,
                IDProy = idProy
            };
            return View(model);
        }

        [HttpPost]

        public ActionResult Edit(NuevaEtapaModel model)
        {
            if (!string.IsNullOrEmpty(model.Nombre))
            {
                try
                {
                    var proyecto = _lineaRepository.GetProyecto(model.IDProy);
                    proyecto.Etapas.Where(e => e.ID == model.ID).First().Nombre = model.Nombre;
                    proyecto.Etapas.Where(e => e.ID == model.ID).First().Duracion = model.duracion;

                    _lineaRepository.Update(proyecto.LineaDeProduccion);
                    _lineaRepository.UnitOfWork.SaveChanges();
                    TempData["success"] = "Etapa modificada";
                    return RedirectToAction("index", new { idLinea=model.IDLinea,idProy=model.IDProy }); 
                }
                catch(Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }
            }
            else
            {
                TempData["error"] = "Debe completar ambos campos";
                return View(model);
            }
        }

        public ActionResult Delete(int idLinea, int idProy, int idEtapa)
        {
            var etapa = _lineaRepository.GetEtapa(idEtapa);
            var proyecto = _lineaRepository.GetProyecto(etapa.IDProyecto);
            var model = new NuevaEtapaModel()
            {
                Nombre = etapa.Nombre,
                ID = idEtapa
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(NuevaEtapaModel model)
        {
            try
            {
                var etapa = _lineaRepository.GetEtapa(model.ID);
                _lineaRepository.DeleteEtapa(etapa);
                _lineaRepository.UnitOfWork.SaveChanges();
                TempData["success"] = "Etapa eliminada";
                return RedirectToAction("Index", new { idLinea=model.IDLinea, idProy = model.IDProy });
            }
            catch(Exception ex)
            {
                TempData["error"] = ex.Message;
                return View(model);
            }
        }

        public ActionResult Tecnologias(int idLinea, int idEtapa)
        {
            var etapa = _lineaRepository.GetEtapa(idEtapa);
            var model = new EtapaTecnologiaModel()
            {
                Etapa = etapa,
                Tecnologias = etapa.Tecnologias.ToList(),
                IDLinea = idLinea
            };
            return View(model);

        }

        public ActionResult NewTecno(int idLinea, int idProy, int idEtapa)
        {
            var etapa = _lineaRepository.GetEtapa(idEtapa);
            var tecno = _tecnoRepository.ListTecnologias();
            var model = new NuevaEtapaTecnologiaModel()
            {
                IDLinea = idLinea,
                IDProy = idProy,
                IDEtapa = idEtapa,
                NombreTecnologia = etapa.Nombre,
                Tecnologias = tecno
            };
            return View(model);
        }

        [HttpPost]

        public ActionResult NewTecno(NuevaEtapaTecnologiaModel model)
        {
            try
            {
                var lineaBuscada = _lineaRepository.GetLinea(model.IDLinea);
                var etapaBuscada = _lineaRepository.GetEtapa(model.IDEtapa);
                var tecnoBuscada = _tecnoRepository.GetTecnologia(model.IDTecno);
                etapaBuscada.pushTecnologia(tecnoBuscada);
                _lineaRepository.Update(lineaBuscada);
                _lineaRepository.UnitOfWork.SaveChanges();

                TempData["success"] = "Tecnologia agregada";
                return RedirectToAction("Tecnologias", new { idLinea= model.IDLinea, idProy = model.IDProy, idEtapa = model.IDEtapa});
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return View(model);
            }
        }

        public ActionResult DeleteTecno(int idLinea, int idTecno, int idEtapa)
        {
            var etapaBuscada = _lineaRepository.GetEtapa(idEtapa);
            var tecnoBuscada = _tecnoRepository.GetTecnologia(idTecno);

            var model = new NuevaEtapaTecnologiaModel()
            {
                NombreTecnologia = tecnoBuscada.nombre,
                IDEtapa = idEtapa,
                IDProy = etapaBuscada.IDProyecto,
                IDLinea = idLinea
            };
            return View(model);
        }

        [HttpPost]

        public ActionResult DeleteTecno(NuevaEtapaTecnologiaModel model)
        {
            try
            {
                var lineaBuscada = _lineaRepository.GetLinea(model.IDLinea);
                var etapaBuscada = _lineaRepository.GetEtapa(model.IDEtapa);
                var tecnoBuscada = etapaBuscada.Tecnologias.First(t => t.ID == model.IDTecno);
                etapaBuscada.pullTecnologia(tecnoBuscada);
                _lineaRepository.Update(lineaBuscada);
                _lineaRepository.UnitOfWork.SaveChanges();

                TempData["success"] = "Tecnologia borrada";
                return RedirectToAction("Tecnologias", new { idLinea= model.IDLinea, idEtapa= model.IDEtapa});
            }catch(Exception ex)
            {
                TempData["error"] = ex.Message;
                return View(model);
            }
        }
    }
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Controllers/TecnologiasController.cs
using EscuelaNet.Presentacion.Proyectos.Web.Infraestructura;
using EscuelaNet.Presentacion.Proyectos.Web.Models;
using EscuelaNet.Dominio.Proyectos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EscuelaNet.Presentacion.Proyectos.Web.Controllers
{
    public class TecnologiasController : Controller
    {
        private ITecnologiaRepository _tecnoRepository;
        public TecnologiasController(ITecnologiaRepository tecnoRepository)
        {
            _tecnoRepository = tecnoRepository;
        }
        // GET: Tecnologias
        public ActionResult Index()
        {
            var Tecno = _tecnoRepository.ListTecnologias();
            var model = new TecnologiasIndexModel()
            {
                Nombre = "Prueba",
                Tecnologias = Tecno
            };
            return View(model);
        }

        public ActionResult New()
        {
            var model = new NuevaTecnologiaModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult New(NuevaTecnologiaModel model)
        {
            if (!string.IsNullOrEmpty(model.Nombre))
            {
                try
                {
                    _tecnoRepository.Add(new Tecnologias(model.Nombre));
                    _tecnoRepository.UnitOfWork.SaveChanges();   //Aqui el error
                    TempData["success"] = "Tecnología creada";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }
            }
            else
            {
                TempData["error"] = "Campo nombre vacío";
                return View(model);
            }
        }

        public ActionResult Edit(int id)
        {
            var Tecno = _tecnoRepository.GetTecnologia(id);
            var model = new NuevaTecnologiaModel()
            {
                Nombre = Tecno.nombre,
                ID = id

            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(NuevaTecnologiaModel model)
        {
            if(!string.IsNullOrEmpty(model.Nombre))
            {
                try
                {
                    var tecno = _tecnoRepository.GetTecnologia(model.ID);
                    tecno.nombre = model.Nombre;
                    _tecnoRepository.Update(tecno);
                    _tecnoRepository.UnitOfWork.SaveChanges();
                    TempData["success"] = "Tecnología editada";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }
            }
            else
            {
                TempData["error"] = "Campo nombre vacío";
                    return View(model);
            }
        }

        public ActionResult Delete(int id)
        {

            var Tecno = _tecnoRepository.GetTecnologia(id);
            var model = new NuevaTecnologiaModel()
            {
                Nombre = Tecno.nombre,
                ID = id
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult Delete(NuevaTecnologiaModel model)
        {
            try
            {
                var tecno = _tecnoRepository.GetTecnologia(model.ID);
                _tecnoRepository.Delete(tecno);
                _tecnoRepository.UnitOfWork.SaveChanges();
                TempData["success"] = "Tecnología eliminada";
                return RedirectToAction("Index");
            }catch(Exception ex)
            {
                TempData["error"] = ex.Message;
                return View(model);
            }
        }
    }
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Etapas/Delete - Copia.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevaEtapaTecnologiaModel

@{
    ViewBag.Title = "Delete";
}


<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Borrar Tecnologia @Model.NombreTecnologia</h3>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IDLinea)
                @Html.HiddenFor(model => model.IDProy)
                @Html.HiddenFor(model => model.IDEtapa)
                @Html.HiddenFor(model => model.IDTecno)
                <div class="box-body">
                    <p>
                        ¿Tecnologia a Borrar: "@Model.NombreTecnologia"?
                    </p>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Aceptar</button>
                    <a href="/Etapas/Tecnologias/?idEtapa=@Model.IDEtapa" class="btn btn-primary">Cancelar</a>
                </div>
            }

        </div>
        <!-- /.box -->
    </div>

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Etapas/Delete.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevaEtapaModel

@{
    ViewBag.Title = "Borrar";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Borrar proyecto</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm())
                {   
                    
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    <div class="box-body">
                        <p>
                            ¿Está seguro de borrar la etapa <strong>"@Model.Nombre"</strong> ?
                        </p>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>

}
<div>
    <a href="/Etapas/Index/?idLinea=@Model.IDLinea&idProy=@Model.IDProy">Volver a lista de Etapas</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Etapas/DeleteTecno.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevaEtapaTecnologiaModel

@{
    ViewBag.Title = "Delete";
}


<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Borrar Tecnologia @Model.NombreTecnologia</h3>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IDLinea)
                @Html.HiddenFor(model => model.IDProy)
                @Html.HiddenFor(model => model.IDEtapa)
                @Html.HiddenFor(model => model.IDTecno)
                <div class="box-body">
                    <p>
                        ¿Tecnologia a Borrar: "@Model.NombreTecnologia"?
                    </p>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Aceptar</button>
                    <a href="/Etapas/Tecnologias/?idEtapa=@Model.IDEtapa" class="btn btn-primary">Cancelar</a>
                </div>
            }

        </div>
        <!-- /.box -->
    </div>

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Etapas/Edit.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevaEtapaModel

@{
    ViewBag.Title = "Editar";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Nuevo proyectos</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
           
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    @Html.HiddenFor(model => model.IDLinea)
                    @Html.HiddenFor(model => model.IDProy)
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Este campo es obligatorio.", data_minlength = "1" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.duracion, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.duracion, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Este campo es obligatorio.", data_minlength = "1" } })
                            @Html.ValidationMessageFor(model => model.duracion, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Editar</button>
                    </div>
                    <div class="box-footer">
                        <a href="/Home/Index">Cancelar</a>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>

}
<div>
    <a href="/Etapas/Index/?idLinea=@Model.IDLinea&idProy=@Model.IDProy">Volver a lista de Etapas</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Etapas/Index.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.EtapaIndexModel

@{
    ViewBag.Title = "Index";
    var x = 1;
    for (var i = 10; i > 0; i--)
    {
        x *= i;
    }
}

<div class="row">
        <div class="col-md-6">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Etapas</h3>
                <label class="text-success">@TempData["success"]</label>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-bordered">
                  <tbody>
                      <tr>
                          <th style="width: 10px">#</th>
                          <th>Etapas</th>
                          <th>Duracion</th>
                          <th>Acciones</th>
                      </tr>
                      @foreach (var etapa in Model.Etapas)
                      {
                          <tr>
                              <td>@etapa.ID</td>
                              <td>@etapa.Nombre</td>
                              <td>@etapa.Duracion</td>
                              <td>
                                  <a href="/Etapas/Tecnologias/?idLinea=@Model.IDLinea&idEtapa=@etapa.ID" title="Tecnologias" class="btn btn-toolbar">
                                      <label class="label bg-gray"><i class="fa fa-edit"></i> Tecnologias</label>
                                  </a>
                                  <a href="/Etapas/edit/?idLinea=@Model.IDLinea&idProy=@Model.IDProy&idEtapa=@etapa.ID" title="Editar" class="btn btn-toolbar">
                                      <label class="label bg-gray"><i class="fa fa-edit"></i> Editar</label>
                                  </a>
                                  <a href="/Etapas/delete/?idLinea=@Model.IDLinea&idProy=@Model.IDProy&idEtapa=@etapa.ID" title="borrar" class="btn btn-toolbar">
                                      <label class="label bg-gray"><i class="fa fa-remove"></i> Borrar</label>
                                  </a>
                              </td>
                          </tr>

                      }
                      <tr>
                          <td></td>
                          <td></td>
                          <td>
                              <a href="/Etapas/New/?id=@Model.IDProy" title="Nuevo" class="btn btn-toolbar">
                                  <label class="label bg-gray"><i class="fa fa-plus"></i> Nuevo</label>
                              </a>
                          </td>
                      </tr>
                  </tbody></table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
              <ul class="pagination pagination-sm no-margin pull-right">
                <li><a href="#">«</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">»</a></li>
              </ul>
            </div>
          </div>
          <!-- /.box -->

          <!-- /.box -->
        </div>
        <!-- /.col -->
        <!-- /.col -->
      </div>
      <a href="/Proyectos/Index/@Model.IDLinea">Volver a lista de Proyectos</a>
@section Scripts{
    <script>
    </script>
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Etapas/New - Copia.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevaEtapaModel

@{
    ViewBag.Title = "New";
}




    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Nuevo Tecnología</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm("New", "Tecnologia", null,
           FormMethod.Post, new { role = "form", data_toggle = "validator", @id = "myForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IDLinea)
                    @Html.HiddenFor(model => model.IDProy)
                    

                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Debe ingresar el nombre la Etapa.", data_minlength = "5" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "help-block with-errors" })
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.duracion, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.duracion, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Debe ingresar la duración de la Etapa", data_minlength = "1" } })
                            @Html.ValidationMessageFor(model => model.duracion, "", new { @class = "help-block with-errors" })
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>
<div>
    <a href="/Etapas/Index/?idLinea=@Model.IDLinea&idProy=@Model.IDProy">Volver a lista de Etapas</a>
</div>

@section Scripts {
    <script src="~/lib/1000hz-bootstrap-validator/validator.js"></script>
    <script>
        $(document).ready(function () {
            $('#myForm').validator()
        });
    </script>
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Etapas/New.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevaEtapaModel

@{
    ViewBag.Title = "New";
}




    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Nuevo etapa</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm("New", "Etapas", null,
           FormMethod.Post, new { role = "form", data_toggle = "validator", @id = "myForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IDLinea)
                    @Html.HiddenFor(model => model.IDProy)
                    

                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Debe ingresar el nombre la Etapa.", data_minlength = "5" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "help-block with-errors" })
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.duracion, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.duracion, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Debe ingresar la duración de la Etapa", data_minlength = "1" } })
                            @Html.ValidationMessageFor(model => model.duracion, "", new { @class = "help-block with-errors" })
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>
<div>
    <a href="/Etapas/Index/?idLinea=@Model.IDLinea&idProy=@Model.IDProy">Volver a lista de Etapas</a>
</div>

@section Scripts {
    <script src="~/lib/1000hz-bootstrap-validator/validator.js"></script>
    <script>
        $(document).ready(function () {
            $('#myForm').validator()
        });
    </script>
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Etapas/NewTecno.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevaEtapaTecnologiaModel

@{
    ViewBag.Title = "New";
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Nueva Tecnologia</h3>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm("NewTecno", "Etapas", new { }, FormMethod.Post, new { role = "form", data_toggle = "validator", @id = "myform" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IDLinea)
                @Html.HiddenFor(model => model.IDProy)
                @Html.HiddenFor(model => model.IDEtapa)
                <div class="box-body">

                    <div class="form-group">
                        @Html.LabelFor(model => model.Tecnologias, htmlAttributes: new { @class = "control-label col-md-2" })
                        <select name="IDTecno" class="form-control col-md-2">
                            @foreach (var tecno in Model.Tecnologias)
                            {
                                <option value="@tecno.ID">@tecno.nombre</option>
                            }
                        </select>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="~/Etapa/Index/?idProy=@Model.IDProy" class="btn btn-primary">Cancelar</a>
                </div>
            }

        </div>
        <!-- /.box -->
    </div>

</div>

@section Scripts {
    <script src="~/lib/1000hz-bootstrap-validator/validator.js"></script>
    <script>
      $(document).ready(function () {
          $('#myForm').validator()
      });

    </script>

}