src/Presentacion/EscuelaNet.Presentacion.Clientes.Web/Controllers/DireccionesController.cs
using EscuelaNet.Aplicacion.Clientes.Commands.DireccionCommand;
using EscuelaNet.Aplicacion.Clientes.QueryServices;
using EscuelaNet.Dominio.Clientes;
using EscuelaNet.Presentacion.Clientes.Web.Models;
using EsculaNet.Infraestructura.Clientes;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MediatR;

namespace EscuelaNet.Presentacion.Clientes.Web.Controllers
{
    public class DireccionesController : Controller
    {        
        private IDireccionesQuery _direccionesQuery;
        private IUnidadesQuery _unidadesQuery;
        private IMediator _mediator;

        public DireccionesController( 
                IDireccionesQuery direccionesQuery,
                IUnidadesQuery unidadesQuery,
                IMediator mediator)
        {            
            _direccionesQuery = direccionesQuery;
            _unidadesQuery = unidadesQuery;
            _mediator = mediator;
        }

        public ActionResult Index(int id)
        {       
            var direcciones = _direccionesQuery.ListDirecciones(id);

            if (direcciones.Count!=0)
            {
                var model = new DireccionesIndexModel()
                {
                    Titulo = "Direcciones de la Unidad '" + direcciones[0].RazonSocialUnidad + "'",
                    Direcciones = direcciones,
                    IdUnidad = id,
                    IdCliente = direcciones[0].IdCliente
                };

                return View(model);
            }
            else
            {
                var unidad = _unidadesQuery.GetUnidadDeNegocio(id);
                TempData["error"] = "Unidad sin direcciones";
                return RedirectToAction("../Unidades/Index/"+unidad.IdCliente);
            }
        }

        public ActionResult New(int id)
        {
            var unidad = _unidadesQuery.GetUnidadDeNegocio(id);
            var model = new NuevaDireccionModel()
            {
                Titulo = "Nueva Direccion para la  Unidad '"+unidad.RazonSocial+"'",
                IdUnidad = id
            };
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> New(NuevaDireccionCommand model)
        {
            var exito = await _mediator.Send(model);

            if (exito.Succes)
            {
                TempData["success"] = "Direccion Creada";
                return RedirectToAction("Index/" + model.IdUnidad);
            }
            else
            {
                TempData["error"] = exito.Error;
                var modelReturn = new NuevaDireccionModel()
                {
                    Domicilio = model.Domicilio,
                    Localidad=model.Localidad,
                    Provincia=model.Provincia,
                    Pais=model.Pais,
                    IdUnidad = model.IdUnidad,                    
                };
                return View(modelReturn);
            }            
        }
        
        public ActionResult Edit(int id)
        {
            var direccion = _direccionesQuery.GetDireccion(id);
            if (direccion==null)
            {
                TempData["error"] = "Id no valido";
                return RedirectToAction("../Clientes/Index");
            }
            else
            {                
                var unidad = _unidadesQuery.GetUnidadDeNegocio(direccion.IdUnidadDeNegocio);
                var model = new NuevaDireccionModel()
                {
                    Titulo="Editar una Direccion  de la Unidad '"+unidad.RazonSocial+"' del Cliente '"+ unidad.RazonSocialCliente+"'",                    
                    IdUnidad = direccion.IdUnidadDeNegocio,
                    IdDireccion = id,
                    Domicilio = direccion.Domicilio,
                    Localidad = direccion.Localidad,
                    Provincia = direccion.Provincia,
                    Pais = direccion.Pais

                };

                return View(model);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Edit(EditDireccionCommand model)
        {
            var exito = await _mediator.Send(model);

            if (exito.Succes)
            {
                TempData["success"] = "Direccion Editada";
                return RedirectToAction("Index/" + model.IdUnidad);
            }
            else
            {
                TempData["error"] = exito.Error;
                var modelReturn = new NuevaDireccionModel()
                {
                    Domicilio = model.Domicilio,
                    Localidad = model.Localidad,
                    Provincia = model.Provincia,
                    Pais = model.Pais,
                    IdUnidad = model.IdUnidad,
                    IdDireccion=model.IdDireccion
                };
                return View(modelReturn);
            }
                       
        }

        public ActionResult Delete(int id)
        {
            var direccion = _direccionesQuery.GetDireccion(id);

            if (direccion==null)
            {
                TempData["error"] = "Id no valido";
                return RedirectToAction("../Clientes/Index");
            }
            else
            {
                var unidad = _unidadesQuery.GetUnidadDeNegocio(direccion.IdUnidadDeNegocio);
                var model = new NuevaDireccionModel()
                {
                    Titulo = "Borrar una Direccion  de la Unidad '" + unidad.RazonSocial + "' del Cliente '" + unidad.RazonSocialCliente + "'",                   
                    IdUnidad = direccion.IdUnidadDeNegocio,
                    IdDireccion = id,
                    Domicilio = direccion.Domicilio,
                    Localidad = direccion.Localidad,
                    Provincia = direccion.Provincia,
                    Pais = direccion.Pais

                };
                return View(model);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Delete(DeleteDireccionCommand model)
        {
            var exito = await _mediator.Send(model);

            if (exito.Succes)
            {
                TempData["success"] = "Direccion Borrada";
                return RedirectToAction("Index/" + model.IdUnidad);
            }
            else
            {
                TempData["error"] = exito.Error;
                var modelReturn = new NuevaDireccionModel()
                {
                    Domicilio = model.Domicilio,
                    Localidad = model.Localidad,
                    Provincia = model.Provincia,
                    Pais = model.Pais,
                    IdUnidad = model.IdUnidad,
                    IdDireccion = model.IdDireccion
                };
                return View(modelReturn);
            }           

        }

    }
}

src/Presentacion/EscuelaNet.Presentacion.Clientes.Web/Views/Direcciones/Delete.cshtml
@model EscuelaNet.Presentacion.Clientes.Web.Models.NuevaDireccionModel

@{
    ViewBag.Title = "Borrar";
}


    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">@Model.Titulo</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IdUnidad)
                    @Html.HiddenFor(model => model.IdDireccion)
                    <div class="box-body">
                        <p>
                            ¿Está seguro de borrar la Direccion "@Model.Domicilio - @Model.Localidad"?
                        </p>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                        <a href="~/direcciones/index/@Model.IdUnidad" class="btn btn-primary">Cancelar</a>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Clientes.Web/Views/Direcciones/Edit.cshtml
@model EscuelaNet.Presentacion.Clientes.Web.Models.NuevaDireccionModel

@{
    ViewBag.Title = "Editar";
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">@Model.Titulo</h3>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm("Edit", "Direcciones", new { }, FormMethod.Post, new { role = "form", data_toggle = "validator", @id = "myform" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IdUnidad)
                @Html.HiddenFor(model => model.IdDireccion)
                <div class="box-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Domicilio, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Domicilio, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Complete el campo Domicilio" } })
                        @Html.ValidationMessageFor(model => model.Domicilio, "", new { @class = "text-danger" })
                        <div class="help-block with-errors"></div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Localidad, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Localidad, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Complete el campo Localidad" } })
                        @Html.ValidationMessageFor(model => model.Localidad, "", new { @class = "text-danger" })
                        <div class="help-block with-errors"></div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Provincia, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Complete el campo Provincia" } })
                        @Html.ValidationMessageFor(model => model.Provincia, "", new { @class = "text-danger" })
                        <div class="help-block with-errors"></div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Pais, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Complete el campo Pais" } })
                        @Html.ValidationMessageFor(model => model.Pais, "", new { @class = "text-danger" })
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Aceptar</button>
                    <a href="~/direcciones/index/@Model.IdUnidad" class="btn btn-primary">Cancelar</a>
                </div>
            }

        </div>
        <!-- /.box -->
    </div>

</div>

@section Scripts {
    <script src="~/lib/1000hz-bootstrap-validator/validator.js"></script>
    <script>
      $(document).ready(function () {
          $('#myForm').validator()
      });

    </script>

}

src/Presentacion/EscuelaNet.Presentacion.Clientes.Web/Views/Direcciones/Index.cshtml
@model EscuelaNet.Presentacion.Clientes.Web.Models.DireccionesIndexModel
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-lg-10">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">@Model.Titulo</h3>
                <label class="text-success">@TempData["success"]</label>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>Domicilio</th>
                            <th>Localidad</th>
                            <th>Provincia</th>
                            <th>Pais</th>                            
                            <th>Acciones</th>
                        </tr>
                        @foreach (var direccion in Model.Direcciones)
                        {
                    <tr>
                        <td>@direccion.ID</td>
                        <td>@direccion.Domicilio</td>
                        <td>@direccion.Localidad</td>
                        <td>@direccion.Provincia</td>
                        <td>@direccion.Pais</td>                        
                        
                        
                        <td>
                            <a href="/Direcciones/edit/@direccion.ID" title="Editar" class="btn btn-toolbar">
                                <label class="label bg-gray"><i class="fa fa-edit"></i> Editar</label>
                            </a>
                            <a href="/Direcciones/delete/@direccion.ID" title="Borrar" class="btn btn-toolbar">
                                <label class="label bg-gray"><i class="fa fa-remove"></i> Borrar</label>
                            </a>
                        </td>
                    </tr>

                        }
                        <tr>
                            <td colspan="9">
                                <a href="~/Direcciones/new/@Model.IdUnidad" title="Nuevo" class="btn btn-primary">
                                     Nuevo
                                </a>
                            </td>
                           
                        </tr>
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
                <ul class="pagination pagination-sm no-margin pull-right">
                    <li><a href="#">«</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">»</a></li>
                </ul>
            </div>
        </div>
        <!-- /.box -->
        <!-- /.box -->
    </div>
    <!-- /.col -->
    <!-- /.col -->
</div>

<div>
    @Html.ActionLink("Volver a Unidad", "../Unidades/Index/"+Model.IdCliente)
</div>

@section Scripts{
    <script>
    </script>
}

src/Presentacion/EscuelaNet.Presentacion.Clientes.Web/Views/Direcciones/New.cshtml
@model EscuelaNet.Presentacion.Clientes.Web.Models.NuevaDireccionModel

@{    
    ViewBag.Title = "New";
}

    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">@Model.Titulo</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm("New", "Direcciones", new { }, FormMethod.Post, new { role = "form", data_toggle = "validator" , @id="myform"}))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="box-body">
                <div class="form-group">
                    @Html.HiddenFor(model => model.IdUnidad)
                    @Html.LabelFor(model => model.Domicilio, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Domicilio, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Complete el campo Domicilio" } })
                    @Html.ValidationMessageFor(model => model.Domicilio, "", new { @class = "text-danger" })
                    <div class="help-block with-errors"></div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Localidad, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Localidad, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Complete el campo Localidad" } })
                    @Html.ValidationMessageFor(model => model.Localidad, "", new { @class = "text-danger" })
                    <div class="help-block with-errors"></div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Provincia, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Complete el campo Provincia" } })
                    @Html.ValidationMessageFor(model => model.Provincia, "", new { @class = "text-danger" })
                    <div class="help-block with-errors"></div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Pais, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Complete el campo Pais" } })
                    @Html.ValidationMessageFor(model => model.Pais, "", new { @class = "text-danger" })
                    <div class="help-block with-errors"></div>
                </div>
                
            </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                        <a href="~/direcciones/index/@Model.IdUnidad" class="btn btn-primary" >Cancelar</a>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>

@section Scripts {
  <script src="~/lib/1000hz-bootstrap-validator/validator.js"></script>
  <script>
      $(document).ready(function () {
          $('#myForm').validator()
      });
     
  </script>

}